### ISSUE TITLE
Numpad Colors

### ISSUE THREAD

**Issue by g0vin-d** [ivantbv/calculator#1]
Numpad colors aren't visible

**Comment by ivantbv** [comment]
Hi, @g0vin-d thank you very much for the issue.
Could you specify what exactly isn't visible? The buttons with the numbers are supposed to be white and the buttons with the operators are orange-ish. 
This is how the UI is supposed to look:
<img width="347" alt="Capture" src="https://user-images.githubusercontent.com/65010090/110346943-e6ee1100-8051-11eb-957d-58d2870c2607.PNG">
If the colors look different or something is off, please post a picture so I can deal with the issue.
Or if you have suggestions regarding how the UI can be improved, please let me know.

Thank you for your cooperation 💯

**Comment by g0vin-d** [comment]
well, i checked your site again 
its fine now
